spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mangas1
    username: root
    password: Marcos@123
  jpa:
     
    hibernate:
      ddl-auto: update
      generate-ddl: true
    show-sql: true
