spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mangas
    username: root
    password: Marcos@123
  jpa:
    open-in-view: false  
    hibernate:
      ddl-auto: update
      generate-ddl: true
    show-sql: true
